### ISSUE TITLE
STL and STEP file icons

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercad/JupyterCAD#535]
It seems that the file icon is not showing up in the tab title for STL and STEP files.

On a separate note, it would probably make sense to not use the JupyterCAD logo for these file types, but use a different one for each.

**Comment by trungleduc** [comment]
https://www.flaticon.com/free-icon/stl_9811308?term=stl+file&page=1&position=10&origin=search&related_id=9811308
https://www.flaticon.com/free-icon/stp_9811307?term=stp+file&page=1&position=3&origin=search&related_id=9811307

These icons look good

**Comment by o314** [comment]
Here they are :

![Image](https://github.com/user-attachments/assets/835df6f2-f235-43f4-b934-41f0413e15ca)

![Image](https://github.com/user-attachments/assets/dd594bb7-1ffa-4866-a847-3155716fe39a)

**Comment by martinRenou** [comment]
Nice, thanks @o314! Did you make those yourself?

Only comment: the round corners are not the same for the underlying file icon and the filename label:

![Image](https://github.com/user-attachments/assets/28f4f122-e9e7-40ff-90f1-751e79d1e6ab)

Otherwise it looks great!

**Comment by SylvainCorlay** [comment]
@o314 @martinRenou thank you for your work on the icon.

I have a comment on the design: I think that it would look better with a sans-serif font for STL and STP.

**Comment by o314** [comment]
OK. The font was not the good one since i have not found any probing setup in jupyter repo.
Of course, this has to be reworked - however this proto font was already sans serif.

Here is a file with variations on the font ; the formers are more cad oriented ; the later more commons.
If you 've got a jupyter specific one. point it up, i will brush up the icons

Last line is a more comprehensive rework, i finally prefer.
The current design tends to be overwhelmed with details . So i merge all backs layers into a unique sheet, common in cad
To reinforce the cad environment again, i've added a symbol that can be either understood as a drawing board or as a crane, so it encompasses the whole lifecycle of cad. The back layer is similar to the jupyter commons (same stroke, stroke width, dims) but not exactly due to the merge of back layers.

![Image](https://github.com/user-attachments/assets/5bb7f01d-7b8d-49a9-845c-65932f8e77dd)

[jupytercad icons, curved.pdf](https://github.com/user-attachments/files/17623725/jupytercad.icons.curved.pdf)

The display is a rasterized shot, the file is a vectorized one.
The design file is not svg. Tell me what is your choice, i will provide u the corresponding svg file.

**Comment by arjxn-py** [comment]
Super duper @o314, these looks awesome.
I like almost all of them. Hence don't have a strong opinion on any single design, tho i think the below two rows are not going to align well with the minimal design :)

I'll leave it up on others to choose any one. So Good :)

**Comment by martinRenou** [comment]
Thanks a lot @o314 that's very much appreciated! Same opinion as @arjxn-py on this, they all look good and I also believe the last two rows don't match the rest of the JupyterLab design.

**Comment by SylvainCorlay** [comment]
I agree with @martinRenou that the onces matchings the JupyterLab design would be a better choice. Regarding the choice of font, I would go for a thick one because the thin versions may not be very readable at small sizes.

**Comment by o314** [comment]
ok. the 3rd and 4th columns are the declension for the bold font of the same family when available

**Comment by martinRenou** [comment]
@o314 do you have an svg version of your icons handy?

**Comment by o314** [comment]
Here are the ones that have been vectorized from fira mono bold

![Image](https://github.com/user-attachments/assets/e347031d-6ab1-4073-9734-7e41af6f1acd)

![Image](https://github.com/user-attachments/assets/3b00f92f-e125-46cc-9102-ef94c4b00dc8)

**Comment by martinRenou** [comment]
This is fixed! Thanks @o314 for the icons, you've been credited for this :)

**Comment by o314** [comment]
You're welcome !
Thanks for your work and kind words too
*In english, from Lyon*
