### ISSUE TITLE
Hiding object by using object tree does not hide the bounding box

### ISSUE THREAD

**Issue by trungleduc** [jupytercad/JupyterCAD#545]
https://github.com/user-attachments/assets/c82f4671-1920-412a-9d0a-541c9cf0fa84

**Comment by martinRenou** [comment]
We may want to look at how we are hiding the mesh.

The bounding box should be part of the associated mesh group:
- if not, we should fix this
- if it is already, are we not hiding the entire mesh group properly?

The bounding box creation may also be misplaced in the current implementation. It should probably be created at the same time as the mesh, and hidden/shown upon selection, instead of re-creating it upon each selection

**Comment by arjxn-py** [comment]
Thanks both, this gives me a good idea & i'd be on it
